[package]
name = "octapus_db"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.0", features = ["api"] }
rusqlite = { version = "0.26", features = ["bundled"] }
tokio = { version = "1", features = ["full"] }
deadpool = { version = "0.9" }
postgres = { version = "0.19" }